### ISSUE TITLE
Closing calculator after normal startup

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcmetrics#1]
None None
    Error adding project:  'NoneType' object has no attribute 'template'
Traceback (most recent call last): 
    File "/usr/local/uvcdat/1.5.1/vistrails/vistrails/gui/uvcdat/workspace.py", line 486, in add_project int(cell[1]), int(cell[2]), plot_type.value))
    File "/usr/local/uvcdat/1.5.1/vistrails/vistrails/gui/uvcdat/project_controller.py", line 588, in vis_was_dropped sheetName, row, col, plot_type, cell)
    File "/usr/local/uvcdat/1.5.1/vistrails/vistrails/packages/uvcdat_cdms/pipeline_helper.py", line 609, in load_pipeline_in_location
    cell.add_plot(get_plot_manager().new_plot(plot_type, ptype, gmName))
    File "/usr/local/uvcdat/1.5.1/vistrails/vistrails/gui/uvcdat/project_controller_cell.py", line 103, in add_plot
    if plot.template is None and len(self.templateQ) > 0:
AttributeError: 'NoneType' object has no attribute 'template'

**Comment by mcenerney1** [comment]
This is no longer an issue.
