### ISSUE TITLE
template names are not necessarily unique

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcmetrics#181]
when running the test test suite it "sometimes" (not always of course) seem to be running into template name conflicts:

```
Traceback (most recent call last):
12:   File "/home/travis/miniconda/bin/diags", line 747, in <module>
12: tmpl canvas1,gms,ovly,onPage: <vcs.Canvas.Canvas object at 0x7f0f56210208> ['scatter', 'yxvsx', 'scatter', 'yxvsx', 'scatter', 'yxvsx', 'scatter', 'yxvsx', 'scatter', 'yxvsx', 'scatter', 'yxvsx'] [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1] 6
12:     run_diags(o)
12:   File "/home/travis/miniconda/bin/diags", line 325, in run_diags
12:     makeplots(res, vcanvas, vcanvas2, varid, fname, plot, package)
12:   File "/home/travis/miniconda/bin/diags", line 417, in makeplots
12:     gmobs, tmobs, tmmobs = return_templates_graphic_methods( vcanvas, gms, ovly, onPage )
12:   File "/home/travis/miniconda/lib/python2.7/site-packages/metrics/frontend/it.py", line 190, in return_templates_graphic_methods
12:     disableLegend=disLegend)
12:   File "/home/travis/miniconda/lib/python2.7/site-packages/metrics/frontend/templatefactory.py", line 448, in build_templates
12:     cpLastTemplate = canvas.createtemplate(lastTemplate.name+'_overlay', lastTemplate.name)
12:   File "/home/travis/miniconda/lib/python2.7/site-packages/vcs/Canvas.py", line 1199, in createtemplate
12:     return vcs.createtemplate(name, source)
12:   File "/home/travis/miniconda/lib/python2.7/site-packages/vcs/manageElements.py", line 86, in createtemplate
12:     name, source = check_name_source(name, source, 'template')
12:   File "/home/travis/miniconda/lib/python2.7/site-packages/vcs/manageElements.py", line 60, in check_name_source
12:     raise vcsError("Error %s object named %s already exists" % (typ, name))
12: vcs.error.vcsError: Error template object named 0_x_0_573_overlay already exists
```

full log is at:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=4350071

**Comment by doutriaux1** [comment]
@jccosta I think you're the one that should take a stab at this. Thanks!

**Comment by jccosta** [comment]
@doutriaux1 Could you clean your cache ( /tmp/*.xml and rm /tmp/*.cache.) and try it again? Jeffrey had the same problem and when he cleaned up his cache, everything worked smooth.

**Comment by doutriaux1** [comment]
@jccosta this occurs somewhat randomly when running the test suite. Most of the times the test suite passes but evryonce in a while it will run into this.

**Comment by jccosta** [comment]
@doutriaux1 I will investigate this further.

**Comment by doutriaux1** [comment]
@jccosta any progress on this? Also every once in a while comibned plots get all mangled up together, I suspect it's related to this:
```
diags --model path=/space1/test_data/alpha6_test_run,climos=yes,type=model --obs "path=/space1/test_data/obs/,climos=yes,filter=f_startswith('NCEP')" --logo no --package AMWG --set 5 --seasons JJA --vars Z3 --outputdir /export/doutriaux1/diags_output/amwg_latest --prefix set5 --postfix NCEP --regions Global --varopts 500
```
does lead to this `sometimes` of course it works `most` of the times...

**Comment by jccosta** [comment]
Hi Charles,

I fixed this problem a while ago. I may have forgotten to push the commit to the repository. This weekend I will take a look on this again and let you know. Sorry for the delay.

**Comment by doutriaux1** [comment]
That would be awesome! Thanks!

**Comment by jccosta** [comment]
@doutriaux1 I pushed the corrections to my branch and also updated it to the current devel branch in uvcmetrics: 563eaa445e75518562d53544966469723b78589e
I tested it generating all set of plots and everything worked fine. This version is also a bit faster than the previous one for set plots 11 and 12, and it has a small memory footprint. But I didn't have time to do more testes. Then I am giving you access to the fork. Feel free to tested it more if you think is necessary and to do the pull request.
Thanks, Joanathas.

**Comment by doutriaux1** [comment]
thanks! will try it shortly.
